language: go
sudo: false
go:
  - 1.x
  - tip
env:
  global:
    - GO111MODULE=on
cache:
  directories:
    - $GOPATH/pkg/mod/cache
install:
  - go build -ldflags "-extldflags '-static' -s -w" -tags netgo ./{cmd,pkg}/...
script:
  - go vet ./{cmd,pkg}/...
  - go test -v -race ./{cmd,pkg}/...
